import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path: string) => readFileSync(new URL(path, import.meta.url), "utf8");
const migration = read("../supabase/migrations/20261005200347_macro03_periodized_week_and_execution_states.sql");
const deterministic = read("../supabase/migrations/20261005203000_macro03_deterministic_periodized_selection.sql");
const weekView = read("../src/components/9fit/WeeklyTrainingView.tsx");
const planning = read("../src/pages/9fit/Planejamento.tsx");
const train = read("../src/pages/9fit/Train.tsx");
const execution = read("../src/components/9fit/WorkoutExecution.tsx");
const protocol = read("../src/pages/9fit/Protocolo.tsx");
const recommendations = read("../src/services/engrenagem/recommendationEngine.ts");
const ron = read("../src/components/9fit/RonConciergeSheet.tsx");
const ronOperations = read("../src/services/ronOperationalCore.ts");
const postWorkout = read("../src/components/9fit/PostWorkoutModal.tsx");

assert.match(migration, /fn_generate_periodized_week/);
assert.match(migration, /WHERE dw\.athlete_id = p_athlete_id AND dw\.workout_date = v_date\s+UNION ALL/);
assert.match(migration, /status IN \('started', 'in_progress', 'paused', 'completed', 'skipped'\)/);
assert.match(migration, /fn_skip_daily_workout_execution/);
assert.match(migration, /only_today_can_be_skipped/);
assert.match(migration, /workout_execution_in_progress/);
assert.match(migration, /week_start_must_be_monday/);
assert.doesNotMatch(migration, /ORDER BY\s+random\s*\(/i);
assert.match(deterministic, /hashtextextended\(e\.id::text \|\| coalesce\(p_seed/);
assert.match(deterministic, /jsonb_array_elements\(v_result\)/);
assert.match(deterministic, /p_aluno_id::text \|\| ':' \|\| p_data::text \|\| ':block9'/);
assert.doesNotMatch(deterministic, /random\s*\(/i);
assert.match(weekView, /fn_get_week_workouts/);
assert.match(weekView, /addWeeks\(weekStart,offset\)/);
assert.match(weekView, /fn_generate_periodized_week/);
assert.match(weekView, /fn_skip_daily_workout_execution/);
assert.match(planning, /\/9fit\/train\?tab=semana&date=/);
assert.match(planning, /addMonths\(month,1\)/);
assert.match(train, /businessDate\(\)/);
assert.match(execution, /businessDate\(\)/);
assert.match(protocol, /businessDate\(\)/);
assert.match(recommendations, /syncScore: number \| null/);
assert.match(ron, /syncScore == null \? "Sem leitura"/);
assert.match(weekView, /selectedDate/);
assert.match(weekView, /PRESCRIÇÃO AUSENTE/);
assert.match(postWorkout, /avg_rpe: rpe/);
assert.doesNotMatch(postWorkout.slice(postWorkout.indexOf(".update({"), postWorkout.indexOf(".eq(\"id\", executionId)")), /(^|\n)\s*rpe,/);
assert.match(ron, /asksToReduceVolume/);
assert.match(ronOperations, /case "ADJUST_TRAINING_VOLUME"/);
assert.match(ronOperations, /workout_execution_in_progress|já foi iniciado ou concluído/);
assert.match(ronOperations, /fn_ajustar_treino_dia/);

console.log("PASS Macro 03: periodized week, safe generation, skip receipts, calendar navigation, São Paulo business date and truthful SYNC states");
